- targets:  # url;humanname;routing;switch
    - http://www.google.com/;google.com;external;internetbox
    - https://github.com/;github.com;external;internetbox
    - https://www.googe.com.ar/;google.com.ar;external;internetbox
